# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucscredentials',
            name='port',
            field=models.IntegerField(),
        ),
    ]
