# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170407_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucssystem',
            old_name='name',
            new_name='ipAddress',
        ),
    ]
