# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170407_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucscredentials',
            old_name='protocal',
            new_name='protocol',
        ),
    ]
