# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170417_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucscredentials',
            old_name='name',
            new_name='cred_name',
        ),
        migrations.RenameField(
            model_name='ucscredentials',
            old_name='password',
            new_name='cred_password',
        ),
        migrations.RenameField(
            model_name='ucscredentials',
            old_name='port',
            new_name='cred_port',
        ),
        migrations.RenameField(
            model_name='ucscredentials',
            old_name='protocol',
            new_name='cred_protocol',
        ),
        migrations.RenameField(
            model_name='ucscredentials',
            old_name='username',
            new_name='cred_username',
        ),
    ]
