# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170417_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucscredentials',
            old_name='timeout',
            new_name='cred_timeout',
        ),
    ]
